### ISSUE TITLE
Why is XBT missing

### ISSUE THREAD

**Issue by frederikbosch** [moneyphp/crypto-currencies#2]

**Comment by slunak** [comment]
XBT is essentially BTC. BTC is more known in crypto world, while XBT is more known in "normal" world. I would suggest to stick to BTC though.

References:

- https://www.exodus.com/news/what-is-xbt/
- https://support.kraken.com/hc/en-us/articles/360001206766-Bitcoin-currency-code-XBT-vs-BTC (even Kraken switches to BTC instead of XBT)

**Comment by frederikbosch** [comment]
Hence, we leave it out here. And since it is not bothering in `moneyphp/money` we leave XBT in there.
